<div class="right" id="toolbar">
	Text size <a href="#" title="Larger text"><img src="<?php echo $this->baseUrl(); ?>image/img/icon-plus.gif" width="20" height="20" alt="" /></a> <a href="#" title="Smaller text"><img src="<?php echo $this->baseUrl(); ?>image/img/icon-minus.gif" width="20" height="20" alt="" /></a>
</div>

<div class="clearer">&nbsp;</div>

<div id="site-title">

	<h1><a href="#">Simple Magazine</a> <span> / News</span></h1>

</div>