<div id="navigation">
				
	<div id="main-nav">

		<ul class="tabbed">
			<li class="current-tab"><a href="#">News</a></li>
			<li><a href="#">Politics</a></li>
			<li><a href="#">Culture</a></li>
			<li><a href="#">Sport</a></li>
			<li><a href="#">Debate</a></li>
			<li><a href="#">Entertainment</a></li>
		</ul>

		<div class="clearer">&nbsp;</div>

	</div>

	<div id="sub-nav">

		<ul class="tabbed">
			<li class="current-tab"><a href="index.html">Frontpage</a></li>
			<li><a href="style-demo.html">Style Demo</a></li>
			<li><a href="two-columns.html">Two Columns</a></li>
			<li><a href="single-column.html">Single Column</a></li>
			<li><a href="archives.html">Archives</a></li>
			<li><a href="empty-page.html">Empty Page</a></li>
		</ul>

		<div class="clearer">&nbsp;</div>

	</div>

</div>